# Generated by Django 5.0 on 2024-01-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brills_backend', '0002_bill_profile_remove_userprofile_user_delete_expense_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'verbose_name_plural': 'Bills'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
